/* >>>>>>>>>>>>>> EXPORT_SERVICE_PROVIDER >>>>>>>>>>>>>>>*/
export const EXPORT_SERVICE_PROVIDER = "EXPORT_SERVICE_PROVIDER";
export const EXPORT_SERVICE_PROVIDER_SUCCESS =
  "EXPORT_SERVICE_PROVIDER_SUCCESS";
export const EXPORT_SERVICE_PROVIDER_FAIL = "EXPORT_SERVICE_PROVIDER_FAIL";
